### ISSUE TITLE
dissection.rb fails on ilo4_101.bin

### ISSUE THREAD

**Issue by saidelike** [airbus-seclab/ilo4_toolbox#11]
I am not sure if it is a problem similar to https://github.com/airbus-seclab/ilo4_toolbox/issues/8

Tested with the latest version: a3e4b312a89adad2ad9833dff79f5d11703227eb

The `dissection.rb script` does not work on `ilo4_101.bin`. At that time it is unclear if it is a quirk of this version or a problem with the script itself. From the output below it looks like it is not able to locate the right number of entries for task 0x10, 0x11 and 0x12:

```
ilo4_toolbox/scripts/iLO4$ ruby dissection.rb ilo4_101.bin_outdir/elf.bin 
ruby: warning: shebang line ending with \r may cause problems
> extract from ilo4_101.bin_outdir/elf.bin
--
[..].

> task 0x0f (C:\ilo4\r101\secmgr\bin\secmgr.elf) - 0x00000039 entries
    range: dw1 0x00 - dw2 0x007 - base 0x00001000 - size 0x0000F000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x005 - base 0x00010000 - size 0x00066000 - id 0x00000122 - .blackbox.elf.text
    range: dw1 0x00 - dw2 0x007 - base 0x00076000 - size 0x00002000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x007 - base 0x00078000 - size 0x000D7000 - id 0x00000123 - .blackbox.elf.data
    range: dw1 0x01 - dw2 0x007 - base 0x00150000 - size 0x00004000 - id 0x00000129 - .blackbox.Initial.stack
    range: dw1 0x01 - dw2 0x007 - base 0x00154000 - size 0x000B4000 - id 0x0000012a - .blackbox.heap
    range: dw1 0x00 - dw2 0x007 - base 0x00208000 - size 0x00010000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x107 - base 0x00218000 - size 0x00008000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x107 - base 0x00220000 - size 0x00004000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x00224000 - size 0x003DC000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x00600000 - size 0x01000000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01600000 - size 0x00180000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x005 - base 0x01780000 - size 0x0002E000 - id 0x00000022 - .libc.so.text
    range: dw1 0x00 - dw2 0x007 - base 0x017ae000 - size 0x00002000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x007 - base 0x017b0000 - size 0x00001000 - id 0x00000125 - .libc.so.data
    range: dw1 0x00 - dw2 0x007 - base 0x017b1000 - size 0x00003000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x007 - base 0x017b4000 - size 0x00001000 - id 0x00000126 - .libc.so.bss
    range: dw1 0x00 - dw2 0x007 - base 0x017b5000 - size 0x0002B000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x005 - base 0x017e0000 - size 0x00007000 - id 0x00000020 - .libINTEGRITY.so.text
    range: dw1 0x00 - dw2 0x007 - base 0x017e7000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x007 - base 0x017e8000 - size 0x00001000 - id 0x00000124 - .libINTEGRITY.so.data
    range: dw1 0x00 - dw2 0x007 - base 0x017e9000 - size 0x00417000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x005 - base 0x01c00000 - size 0x0003B000 - id 0x00000025 - .libevlog.so.text
    range: dw1 0x00 - dw2 0x007 - base 0x01c3b000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x007 - base 0x01c3c000 - size 0x00002000 - id 0x00000127 - .libevlog.so.data
    range: dw1 0x00 - dw2 0x007 - base 0x01c3e000 - size 0x00002000 - id 0xffffffff 
    range: dw1 0x01 - dw2 0x007 - base 0x01c40000 - size 0x00008000 - id 0x00000128 - .libevlog.so.data
    range: dw1 0x00 - dw2 0x007 - base 0x01c48000 - size 0x002B8000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f00000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f01000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f02000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f03000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f04000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f05000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f06000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f07000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f08000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f09000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f0a000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f0b000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f0c000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f0d000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f0e000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f0f000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f10000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f11000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f12000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f13000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f14000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f15000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f16000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f17000 - size 0x00004000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f1b000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f1c000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f1d000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f1e000 - size 0x00001000 - id 0xffffffff 
    range: dw1 0x00 - dw2 0x007 - base 0x01f1f000 - size 0x000E1000 - id 0xffffffff 

> task 0x10 (C:\ilo4\r101\pwrmgr\bin\pwrmgr.elf) - 0x00000000 entries

> task 0x11 (C:\ilo4\r101\webserv\bin\webserv.elf) - 0x00000000 entries

> task 0x12 (C:\ilo4\r101\ribcl\bin\ribcl.elf) - 0x02a4d869 entries
Traceback (most recent call last):
	19: from dissection.rb:355:in `<main>'
	18: from dissection.rb:255:in `list_boottable'
	17: from (eval):1:in `times'
	16: from (eval):1:in `times'
	15: from dissection.rb:263:in `block in list_boottable'
	14: from (eval):1:in `times'
	13: from (eval):1:in `times'
	12: from dissection.rb:264:in `block (2 levels) in list_boottable'
	11: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base.rb:21:in `read'
	10: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base.rb:145:in `read'
	 9: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base.rb:254:in `start_read'
	 8: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base.rb:147:in `block in read'
	 7: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:in `do_read'
	 6: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:in `each'
	 5: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:in `block in do_read'
	 4: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base_primitive.rb:129:in `do_read'
	 3: from (eval):23:in `read_and_return_value'
	 2: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/io.rb:276:in `readbytes'
	 1: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/io.rb:312:in `read'
/var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/io.rb:162:in `read_raw': undefined method `read' for nil:NilClass (NoMethodError)
```

**Comment by saidelike** [comment]
I replicated it on ilo4_105.bin as well.

```
> task 0x10 (pwrmgr.elf) - 0x00000000 entries

> task 0x11 (webserv.elf) - 0x02b4a5f9 entries
Traceback (most recent call last):
	19: from ./ilo4_dissection.rb:419:in `<main>'
	18: from ./ilo4_dissection.rb:316:in `list_boottable'
	17: from (eval):1:in `times'
	16: from (eval):1:in `times'
	15: from ./ilo4_dissection.rb:324:in `block in list_boottable'
	14: from (eval):1:in `times'
	13: from (eval):1:in `times'
	12: from ./ilo4_dissection.rb:325:in `block (2 levels) in list_boottable'
	11: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base.rb:21:in `read'
	10: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base.rb:145:in `read'
	 9: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base.rb:254:in `start_read'
	 8: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base.rb:147:in `block in read'
	 7: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:in `do_read'
	 6: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:in `each'
	 5: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/struct.rb:139:in `block in do_read'
	 4: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/base_primitive.rb:129:in `do_read'
	 3: from (eval):23:in `read_and_return_value'
	 2: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/io.rb:276:in `readbytes'
	 1: from /var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/io.rb:312:in `read'
/var/lib/gems/2.5.0/gems/bindata-2.4.3/lib/bindata/io.rb:162:in `read_raw': undefined method `read' for nil:NilClass (NoMethodError)
[firmware_extract] Failed to run ./ilo4_dissection.rb for firmware/ilo4_105.bin/elf.bin, need to be fixed
```

What seems weird is that it seems that it used to work fine as I actually had files such as `.webserv.elf.data` and `.webserv.elf.text` from a run done a long time ago.

**Comment by alexgzt** [comment]
Reproduced, we'll look into it as soon as possible.

Alex.

**Comment by alexgzt** [comment]
Hi Cédric, 

again quite an interesting issue. It seems that older iLO4 firmware versions (<1.20) are built with Integrity 5.0.11.  Size of TaskInfo structure is smaller.

See commit  https://github.com/airbus-seclab/ilo4_toolbox/commit/fd85669ce9e619052245f3633592015a77732a15

alex
