### ISSUE TITLE
Error in patch_webserver_250.py when insert backdoor!

### ISSUE THREAD

**Issue by MUWASEC** [airbus-seclab/ilo4_toolbox#9]
[+] Patch applied to outdir/bootloader.bin.patched
[+] Patch applied to outdir/kernel_main.bin.patched
Traceback (most recent call last):
  File "./patch_webserver_250.py", line 29, in <module>
    handler_code = asm_sc(f.read())
  File "./patch_webserver_250.py", line 11, in asm_sc
    ks = Ks(KS_ARCH_ARM, KS_MODE_ARM)
NameError: global name 'Ks' is not defined
Traceback (most recent call last):
  File "./ilo4_repack.py", line 18, in <module>
    with open(sys.argv[3], "rb") as f:
IOError: [Errno 2] No such file or directory: 'outdir/elf.bin.patched'
[+] Firmware ready to be flashed

**Comment by alexgzt** [comment]
Hi Muwasec, 

from the traceback above it seems that the Keystone engine is missing from you Python setup.

Best regards,
